var links = [
		{
			"title":"The Googs",
			"links":[
				{
					"text":"Google",
					"link":"https://google.dk/"
				},
				{
					"text":"Gmail",
					"link":"https://mail.google.com/"
				},
				{
					"text":"Drive",
					"link":"https://drive.google.com/drive/my-drive"
				},
				{
					"text":"Keep",
					"link":"https://keep.google.com/"
				},
				{
					"text":"YouTube",
					"link":"https://youtube.com/"
				}
				
			]
		},
		{
			"title":"Social",
			"links":[
				{
					"text":"Facebook",
					"link":"https://www.facebook.com/"
				},
				{
					"text":"Twitter",
					"link":"https://twitter.com/"
				},
				{
					"text":"Pinterest",
					"link":"https://pinterest.com/"
				},
				{
					"text":"Kickstarter",
					"link":"https://kickstarter.com/"
				},
				{
					"text":"Instagram",
					"link":"https://instagram.com/"
				}
			]
		},
		{
			"title":"Work",
			"links":[
				{
					"text":"Trello",
					"link":"https://trello.com/"
				},
				{
					"text":"Dropbox",
					"link":"https://dropbox.com/"
				},
				{
					"text":"GitHub",
					"link":"https://github.com/"
				},
				{
					"text":"SharePoint",
					"link":"https://github.com/"
				},
				{
					"text":"Slack",
					"link":"https://slack.com/"
				}
				,
				{
					"text":"Toggl",
					"link":"https://toggl.com/"
				},
				{
					"text":"1Password",
					"link":"https://1password.com/"
				}
			]
		},
		{
			"title":"Reddit",
			"links":[
				{
					"text":"r/aww",
					"link":"https://reddit.com/r/aww/"
				},
				{
					"text":"r/funny",
					"link":"https://www.reddit.com/r/funny/"
				},
				{
					"text":"r/gaming",
					"link":"https://www.reddit.com/r/gaming/"
				},
				{
					"text":"r/lego",
					"link":"https://www.reddit.com/r/lego/"
				},
				{
					"text":"r/ProgrammerHumor",
					"link":"https://www.reddit.com/r/ProgrammerHumor/"
				}
			]
		},
		{
			"title":"Tools",
			"links":[
				{
					"text":"MetaTags",
					"link":"https://metatags.io/"
				},
				{
					"text":"ahrefs",
					"link":"https://ahrefs.com/"
				}
			]
		},
		{
			"title":"Random",
			"links":[
				{
					"text":"Thingiverse",
					"link":"https://thingiverse.io/"
				},
				{
					"text":"github/VoroDk",
					"link":"https://github.com/VoroDk/"
				},
				{
					"text":"Font Awesome",
					"link":"https://fontawesome.com/"
				},
				{
					"text":"Bootstrap",
					"link":"https://getbootstrap.com/"
				},
				{
					"text":"jQuery",
					"link":"https://api.jquery.com/"
				}

			]
		}
	];
